# [코틀린에서 예외를 다루는 방법]

## try catch finally
~~~kotlin
fun parseIntOrThrow(str: String): Int {
    try {
        return str.toInt()
    } catch (e: NumberFormatException){
        throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다.")
    }
}
~~~
Kotlin에서 try catch finally 는 Java의 syntax가 다르지 않다.

## Checked Exception과 Unchecked Exception
~~~kotlin
class FilePrinter{
    fun readFile(){
        val currentFile = File(".")
        val file = File(currentFile.absolutePath + "/a.txt")
        val reader = BufferedReader(FileReader(file))
        println(reader)
        reader.close()
    }
}
~~~
Kotlin에서는 FileReader 등이 IOException 발생할 수도 있지만  
예제처럼 throws 구문을 사용하지 않아도 된다.  
이유는 Kotlin에서는 Checked Exception과 Unchecked Exception을 구분하지 않는다.  
모두 Unchecked Exception 이다.

## try with resources
~~~kotlin
class FilePrinter{
    fun readFile(path: String){ 
        BufferedReader(FileReader(path)).use{
            reader -> println(reader.readLine())
        }
    }
}
~~~
Kotlin에서는 Java에서 사용하던 try with resources 구문은 없고 use를 사용한다.  
(이후에 좀더 살펴 볼 예정)