## 코틀린에서 예외를 다루는 방법

1. try catch finally 구문
2. Checked Exception과 Unchecked Exception
3. try with resources

## try catch finally 구문

```kotlin
fun parseIntOrThrow(str: String): Int {
  try {
    return str.toInt()
  } catch (e: NumberFormatException) {
    throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다")
  }
}
```
+ toType 으로 형변환 (toInt())
+ new가 없음
+ 포맷팅이 간결함 

```kotlin
fun parseIntOrThrow2(str: String): Int {
  return try {
    str.int()
  } catch (e: NumberFormatException) {
    return null
  }
}
```

## Checked Exception과 Unchecked Exception

```kotlin
fun readFile() {
  val currentFile = File(".")
  val file = File(currentFile.absolutePath + "/a.txt")
  val reader = BufferedReader(FileReader(file))
  println(reader.readLine())
  reader.close()
}
```

+ kotlin에서는 Checked Exception과 Unchecked Exception을 구분하지 않는다. 모두 UnChecked Exception이다.
  - 즉 throws가 없다.

## try with resources

```kotlin
fun readFile(path: String) {
  BufferedReader(FileReader(path)).use { reader ->
    println(reader.readLine())
  }
}
```
+ kotlin에서는 try with resources가 사라지고 use를 사용하는구나 정도만 알아두자, 지금은








